#guess the number


#import random integer function
from random import randint
num = randint(1,100)


#print rules
print("Welcome to the guessing game! Here you will try to guess the random number generated by the system.")
print("The number will be between 1 and 100, including both end values.")

print("You will keep guessing until you guess the random number correctly.")
print("When you guessed correctly, I will tell you along with the number of tries you took.\n")

print("If you are within 10 of the number, I will tell you WARM.")
print("If you are more than 10 from the number, I will tell you COLD.")

print("After your guess, if your next guess is closer to the number, I will tell you WARMER.")
print("If your next guess is further away, I will tell you COLDER.")


#list to store guesses
guess = []


#taking user guess; make sure guess is in-bounds
while True:
    my_guess = int(input("What do you think is the number? "))
    if my_guess<1 or my_guess>100:
        print("The number you selected is out of bounds. Please choose a number within the range of 1 to 100.")
    else:
        print(f"Your guess is {my_guess}.")
        break
    pass


#takes guess and compares it to the generated random number
while True:
    if my_guess==num:
        guess.append(my_guess)
        print(f"You guessed the number! It took {len(guess)} tries.")
        False
        break
        
    else:
        guess.append(my_guess)
        
        if abs(my_guess-num)<=10:
            print("Keep going, your guess is WARM.")
            
            if len(guess)>1:
                if (abs(num-guess[-2]))<(abs(num-guess[-1])):
                    print("You're getting COLDER.")
                    pass
                else:
                    print("You're getting WARMER.")
                    pass
        
        else:
            print("Keep going, your guess is COLD.")
            
            if len(guess)>1:
                if (abs(num-guess[-2]))<(abs(num-guess[-1])):
                    print("You're getting COLDER.")
                    pass
                else:
                    print("You're getting WARMER.")
                    pass
        
        #if guess is wrong, ask for new guess  
        my_guess = int(input("Try a different number. Your new guess is: "))
        if my_guess<1 or my_guess>100:
            print("The number you selected is out of bounds. Please choose a number within the range of 1 to 100.")
        else:
            pass
        
        True
        
    pass
    
#Xiere